name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@yack-security"
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Apply new version
        run: node worker/config/preparePublish.js
      - name: Install dashboard modules
        run: cd app && npm install
      - name: Build dashboard
        run: cd app && npm run build
      - name: Install worker modules
        run: cd worker && npm install
      - name: Build worker
        run: cd worker && npm run build
      - name: Publish package
        run: cd worker && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
