name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=0.0.1" >> $GITHUB_ENV
      - name: Apply new version
        run: node worker/config/preparePublish.js
      - name: Install dashboard modules
        run: cd app && npm install
      - name: Build dashboard
        run: cd app && npm run build
      - name: Install worker modules
        run: cd worker && npm install
      - name: Build worker
        run: cd worker && npm run build
